/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.entryPoint.App;

class TesteAplicacao {
    @Test void aplicacaoPodeSerInstanciada() {
        new App();
    }
}
